name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build web image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: production
          push: true
          tags: "ghcr.io/jeconst/cdsandbox:${{ github.run_number }}"

      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: test
          push: true
          tags: "ghcr.io/jeconst/cdsandbox_test:${{ github.run_number }}"

  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: |
          echo "::add-matcher::.github/matchers/jest.json"
          docker run --rm ghcr.io/jeconst/cdsandbox_test:${{ github.run_number }}
          echo "::remove-matcher owner=jest::"
