name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TAG: "${{ github.run_number }}-${{ github.sha }}"

jobs:
  build:
    environment: production
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Read infrastructure
        run: |
          infrastructure_json=$(bin/terraform output -json deployment_target)
          echo "INFRASTRUCTURE_JSON=$infrastructure_json" >> $GITHUB_ENV

      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: ${{ fromJSON(env.INFRASTRUCTURE_JSON).registry_url }}

      - name: Build
        run: |
          bin/build ${{ env.TAG }}

      - name: Push
        run: |
          bin/push ${{ env.TAG }}

  test:
    environment: production
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Read infrastructure
        run: |
          infrastructure_json=$(bin/terraform output -json deployment_target)
          echo "INFRASTRUCTURE_JSON=$infrastructure_json" >> $GITHUB_ENV

      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: ${{ fromJSON(env.INFRASTRUCTURE_JSON).registry_url }}

      - name: Test
        run: |
          echo "::add-matcher::.github/matchers/jest.json"
          docker run --rm ${{ fromJSON(env.INFRASTRUCTURE_JSON).registry_url }}/cdsandbox-test:${{ env.TAG }}
          echo "::remove-matcher owner=jest::"
