name: Pull Request

on:
  pull_request:
    branches: [ main ]

env:
  TAG: "${{ github.run_number }}-${{ github.sha }}"

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          bin/build "$TAG"

      - name: Test
        run: |
          echo "::add-matcher::.github/matchers/jest.json"
          docker run --rm "cdsandbox-test:$TAG"
          echo "::remove-matcher owner=jest::"
